# Generated by Django 3.0.3 on 2020-02-07 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DerbyArenas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=50)),
                ('vehicle_model', models.IntegerField(db_column='vehicle_model', default=0)),
                ('height_limit', models.DecimalField(db_column='height_limit', decimal_places=25, default=0, max_digits=35)),
            ],
            options={
                'db_table': 'derby_arenas',
            },
        ),
        migrations.CreateModel(
            name='DmArenas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=50)),
                ('active', models.IntegerField()),
            ],
            options={
                'db_table': 'dm_arenas',
            },
        ),
        migrations.CreateModel(
            name='HeavyDmArenas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=50)),
                ('active', models.IntegerField()),
            ],
            options={
                'db_table': 'heavy_dm_arenas',
            },
        ),
        migrations.CreateModel(
            name='HideandseekArenas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=50)),
                ('looking_x', models.DecimalField(db_column='looking_x', decimal_places=25, max_digits=35)),
                ('looking_y', models.DecimalField(db_column='looking_y', decimal_places=25, max_digits=35)),
                ('looking_z', models.DecimalField(db_column='looking_z', decimal_places=25, max_digits=35)),
            ],
            options={
                'db_table': 'hideandseek_arenas',
            },
        ),
        migrations.CreateModel(
            name='OneShootArenas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=50)),
                ('active', models.IntegerField()),
            ],
            options={
                'db_table': 'one_shoot_arenas',
            },
        ),
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=35)),
                ('rank', models.CharField(max_length=255)),
                ('deaths', models.IntegerField(blank=True, default=0)),
                ('kills', models.IntegerField(blank=True, default=0)),
                ('password', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=50)),
                ('ped', models.IntegerField()),
            ],
            options={
                'db_table': 'players',
            },
        ),
        migrations.CreateModel(
            name='PlayersSpawns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.DecimalField(decimal_places=25, max_digits=35)),
                ('y', models.DecimalField(decimal_places=25, max_digits=35)),
                ('z', models.DecimalField(decimal_places=25, max_digits=35)),
            ],
            options={
                'db_table': 'players_spawns',
            },
        ),
        migrations.CreateModel(
            name='RaceArenas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'races_arenas',
            },
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'settings',
            },
        ),
        migrations.CreateModel(
            name='SniperArenas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=50)),
                ('active', models.IntegerField()),
            ],
            options={
                'db_table': 'sniper_arenas',
            },
        ),
        migrations.CreateModel(
            name='TdmArenas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tdm_arenas',
            },
        ),
        migrations.CreateModel(
            name='TdmArenasWeapons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weapon_id', models.PositiveIntegerField()),
                ('ammo', models.PositiveIntegerField()),
                ('arena', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='weapons', to='apilogic.TdmArenas')),
            ],
            options={
                'db_table': 'tdm_arenas_weapons',
            },
        ),
        migrations.CreateModel(
            name='TdmArenasSpawns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.DecimalField(decimal_places=25, max_digits=35)),
                ('y', models.DecimalField(decimal_places=25, max_digits=35)),
                ('z', models.DecimalField(decimal_places=25, max_digits=35)),
                ('team', models.PositiveIntegerField()),
                ('arena', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='spawns', to='apilogic.TdmArenas')),
            ],
            options={
                'db_table': 'tdm_arenas_spawns',
            },
        ),
        migrations.CreateModel(
            name='SniperArenasWeapons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weapon_id', models.PositiveIntegerField()),
                ('ammo', models.PositiveIntegerField()),
                ('arena', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='weapons', to='apilogic.SniperArenas')),
            ],
            options={
                'db_table': 'sniper_arenas_weapons',
            },
        ),
        migrations.CreateModel(
            name='SniperArenasSpawns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.DecimalField(decimal_places=25, max_digits=35)),
                ('y', models.DecimalField(decimal_places=25, max_digits=35)),
                ('z', models.DecimalField(decimal_places=25, max_digits=35)),
                ('arena', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='spawns', to='apilogic.SniperArenas')),
            ],
            options={
                'db_table': 'sniper_arenas_spawns',
            },
        ),
        migrations.CreateModel(
            name='RaceArenasSpawns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.DecimalField(decimal_places=25, max_digits=35)),
                ('y', models.DecimalField(decimal_places=25, max_digits=35)),
                ('z', models.DecimalField(decimal_places=25, max_digits=35)),
                ('vehicle_model', models.IntegerField()),
                ('rotation', models.DecimalField(decimal_places=25, max_digits=35)),
                ('arena', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='spawns', to='apilogic.RaceArenas')),
            ],
            options={
                'db_table': 'races_arenas_spawns',
            },
        ),
        migrations.CreateModel(
            name='RaceArenasCheckpoints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.DecimalField(decimal_places=25, max_digits=35)),
                ('y', models.DecimalField(decimal_places=25, max_digits=35)),
                ('z', models.DecimalField(decimal_places=25, max_digits=35)),
                ('arena', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='checkpoints', to='apilogic.RaceArenas')),
            ],
            options={
                'db_table': 'races_arenas_checkpoints',
            },
        ),
        migrations.CreateModel(
            name='OneShootArenasWeapons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weapon_id', models.PositiveIntegerField()),
                ('ammo', models.PositiveIntegerField()),
                ('arena', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='weapons', to='apilogic.OneShootArenas')),
            ],
            options={
                'db_table': 'one_shoot_arenas_weapons',
            },
        ),
        migrations.CreateModel(
            name='OneShootArenasSpawns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.DecimalField(decimal_places=25, max_digits=35)),
                ('y', models.DecimalField(decimal_places=25, max_digits=35)),
                ('z', models.DecimalField(decimal_places=25, max_digits=35)),
                ('arena', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='spawns', to='apilogic.OneShootArenas')),
            ],
            options={
                'db_table': 'one_shoot_arenas_spawns',
            },
        ),
        migrations.CreateModel(
            name='HideandseekArenasSpawns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.DecimalField(decimal_places=25, max_digits=35)),
                ('y', models.DecimalField(decimal_places=25, max_digits=35)),
                ('z', models.DecimalField(decimal_places=25, max_digits=35)),
                ('arena', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='spawns', to='apilogic.HideandseekArenas')),
            ],
            options={
                'db_table': 'hideandseek_arenas_spawns',
            },
        ),
        migrations.CreateModel(
            name='HeavyDmArenasWeapons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weapon_id', models.PositiveIntegerField()),
                ('ammo', models.PositiveIntegerField()),
                ('arena', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='weapons', to='apilogic.HeavyDmArenas')),
            ],
            options={
                'db_table': 'heavy_dm_arenas_weapons',
            },
        ),
        migrations.CreateModel(
            name='HeavyDmArenasSpawns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.DecimalField(decimal_places=25, max_digits=35)),
                ('y', models.DecimalField(decimal_places=25, max_digits=35)),
                ('z', models.DecimalField(decimal_places=25, max_digits=35)),
                ('arena', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='spawns', to='apilogic.HeavyDmArenas')),
            ],
            options={
                'db_table': 'heavy_dm_arenas_spawns',
            },
        ),
        migrations.CreateModel(
            name='DmArenasWeapons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weapon_id', models.PositiveIntegerField()),
                ('ammo', models.PositiveIntegerField()),
                ('arena', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='weapons', to='apilogic.DmArenas')),
            ],
            options={
                'db_table': 'dm_arenas_weapons',
            },
        ),
        migrations.CreateModel(
            name='DmArenasSpawns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.DecimalField(decimal_places=25, max_digits=35)),
                ('y', models.DecimalField(decimal_places=25, max_digits=35)),
                ('z', models.DecimalField(decimal_places=25, max_digits=35)),
                ('arena', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='spawns', to='apilogic.DmArenas')),
            ],
            options={
                'db_table': 'dm_arenas_spawns',
            },
        ),
        migrations.CreateModel(
            name='DerbyArenasSpawns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.DecimalField(decimal_places=25, max_digits=35)),
                ('y', models.DecimalField(decimal_places=25, max_digits=35)),
                ('z', models.DecimalField(decimal_places=25, max_digits=35)),
                ('rotation', models.DecimalField(decimal_places=25, max_digits=35)),
                ('arena', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='spawns', to='apilogic.DerbyArenas')),
            ],
            options={
                'db_table': 'derby_arenas_spawns',
            },
        ),
    ]
