# Generated by Django 3.0.4 on 2020-03-15 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apilogic', '0002_auto_20200315_1548'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rank',
            new_name='Ranks',
        ),
    ]
