# Generated by Django 3.0.4 on 2020-03-21 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apilogic', '0003_auto_20200315_1611'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopTabData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=32)),
                ('money', models.IntegerField()),
                ('diamonds', models.IntegerField()),
            ],
            options={
                'db_table': 'shop_tabs',
            },
        ),
        migrations.CreateModel(
            name='ShopTabFilterData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=32)),
                ('tab', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='filters', to='apilogic.ShopTabData')),
            ],
            options={
                'db_table': 'shop_tabs_filters',
            },
        ),
        migrations.CreateModel(
            name='ShopEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=50)),
                ('money', models.IntegerField(null=True)),
                ('diamonds', models.IntegerField(null=True)),
                ('name', models.CharField(max_length=32, null=True)),
                ('filter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='entities', to='apilogic.ShopTabFilterData')),
            ],
            options={
                'db_table': 'shop_entities',
            },
        ),
    ]
