# Generated by Django 3.0.4 on 2020-03-21 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apilogic', '0004_shopentity_shoptabdata_shoptabfilterdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopentity',
            name='name',
        ),
        migrations.AddField(
            model_name='shopentity',
            name='display_name',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='shopentity',
            name='filter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='entities', to='apilogic.ShopTabFilterData'),
        ),
        migrations.AlterField(
            model_name='shoptabfilterdata',
            name='tab',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='filters', to='apilogic.ShopTabData'),
        ),
    ]
