# Generated by Django 3.0.4 on 2020-03-21 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apilogic', '0005_auto_20200321_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoptabdata',
            name='column_size',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=2),
        ),
    ]
