# Generated by Django 3.0.4 on 2020-03-22 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apilogic', '0006_shoptabdata_column_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoptabdata',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='apilogic.ShopTabData'),
        ),
    ]
