# Generated by Django 3.0.4 on 2020-03-22 00:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apilogic', '0007_shoptabdata_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoptabdata',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='childs', to='apilogic.ShopTabData'),
        ),
    ]
