# Generated by Django 3.0.4 on 2020-03-22 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apilogic', '0009_auto_20200322_0155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoptabfilterdata',
            name='tab',
        ),
        migrations.AddField(
            model_name='shoptabfilterdata',
            name='tabs',
            field=models.ManyToManyField(to='apilogic.ShopTabData'),
        ),
    ]
