# Generated by Django 3.0.4 on 2020-03-22 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apilogic', '0010_auto_20200322_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoptabfilterdata',
            name='tabs',
            field=models.ManyToManyField(related_name='filters', to='apilogic.ShopTabData'),
        ),
    ]
