# Generated by Django 3.0.4 on 2020-03-22 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apilogic', '0011_auto_20200322_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoptabdata',
            name='description_display_name',
            field=models.CharField(default='TEST', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shoptabdata',
            name='title_display_name',
            field=models.CharField(default='TEST', max_length=64),
            preserve_default=False,
        ),
    ]
