# Generated by Django 3.0.4 on 2020-03-22 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apilogic', '0012_auto_20200322_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoptabdata',
            name='description_display_name',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='shoptabdata',
            name='title_display_name',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
