# Generated by Django 3.0.4 on 2020-03-22 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apilogic', '0013_auto_20200322_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopentity',
            name='ragemp_item_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
