# Generated by Django 3.0.4 on 2020-03-22 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apilogic', '0014_shopentity_ragemp_item_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopentity',
            name='ragemp_item_id',
            field=models.PositiveIntegerField(),
        ),
    ]
