# Generated by Django 3.0.4 on 2020-03-22 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apilogic', '0015_auto_20200322_2109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoptabfilterdata',
            name='tabs',
        ),
        migrations.AddField(
            model_name='shoptabfilterdata',
            name='tab',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='filters', to='apilogic.ShopTabData'),
            preserve_default=False,
        ),
    ]
