# Generated by Django 3.0.4 on 2020-03-31 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apilogic', '0016_auto_20200322_2115'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShopEntity',
            new_name='ShopEntities',
        ),
        migrations.AddField(
            model_name='players',
            name='diamonds',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='players',
            name='money',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
