# Generated by Django 3.0.4 on 2020-04-04 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apilogic', '0017_auto_20200331_1924'),
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_display_name', models.CharField(max_length=64)),
                ('filename', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('date_expire', models.DateTimeField(null=True)),
                ('ragemp_item_id', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'items',
            },
        ),
        migrations.AlterField(
            model_name='shopentities',
            name='filename',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='shopentities',
            name='ragemp_item_id',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='players',
            name='items',
            field=models.ManyToManyField(related_name='items', to='apilogic.Items'),
        ),
        migrations.AddField(
            model_name='shopentities',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apilogic.Items'),
        ),
    ]
