# Generated by Django 3.0.4 on 2020-04-04 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apilogic', '0018_auto_20200404_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='section',
            field=models.CharField(default='weapon', max_length=32),
            preserve_default=False,
        ),
    ]
