# Generated by Django 3.0.4 on 2020-04-04 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('apilogic', '0020_auto_20200404_2236'), ('apilogic', '0021_auto_20200404_2239')]

    dependencies = [
        ('apilogic', '0019_items_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayersItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipped', models.BooleanField(default=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apilogic.Items')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apilogic.Players')),
            ],
            options={
                'db_table': 'players_items',
                'managed': True
            },
        ),
        migrations.AddField(
            model_name='players',
            name='items',
            field=models.ManyToManyField(related_name='items', through='apilogic.PlayersItems', to='apilogic.Items'),
        ),
    ]
