# Generated by Django 3.0.4 on 2020-04-04 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apilogic', '0020_auto_20200404_2236'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='playersitems',
            table='players_items',
        ),
    ]
