# Generated by Django 3.0.4 on 2020-04-04 23:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apilogic', '0020_auto_20200404_2236_squashed_0021_auto_20200404_2239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='players',
            name='items',
        ),
        migrations.AlterField(
            model_name='playersitems',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='apilogic.Players'),
        ),
    ]
