# Generated by Django 3.0.4 on 2020-04-05 00:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apilogic', '0021_auto_20200405_0153'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playersitems',
            options={},
        ),
        migrations.AddField(
            model_name='players',
            name='items',
            field=models.ManyToManyField(related_name='items', through='apilogic.PlayersItems', to='apilogic.Items'),
        ),
        migrations.AlterField(
            model_name='playersitems',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_items', to='apilogic.Items'),
        ),
        migrations.AlterField(
            model_name='playersitems',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apilogic.Players'),
        ),
    ]
