# Generated by Django 3.0.4 on 2020-04-05 01:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apilogic', '0023_auto_20200405_0206'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemsSections',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('column_size', models.DecimalField(decimal_places=1, default=1, max_digits=2)),
            ],
            options={
                'db_table': 'items_sections',
                'managed': True
            },
        ),

        migrations.AddField(
            model_name='items',
            name='days_to_expire',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='items',
            name='sub_section',
            field=models.CharField(default='none', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playersitems',
            name='date_expire',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='items',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='items', to='apilogic.ItemsSections'),
        ),
    ]
