# Generated by Django 3.0.4 on 2020-04-05 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apilogic', '0024_auto_20200405_0338'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemssections',
            options={},
        ),
        migrations.RemoveField(
            model_name='items',
            name='date_expire',
        ),
    ]
