# Generated by Django 3.0.4 on 2020-04-05 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apilogic', '0025_auto_20200405_0348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='sub_section',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
