# Generated by Django 3.0.4 on 2020-04-05 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apilogic', '0026_auto_20200405_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='ragemp_item_id',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
