# Generated by Django 3.0.4 on 2020-04-05 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apilogic', '0027_auto_20200405_1621'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='players',
            name='ped',
        ),
    ]
