# Generated by Django 3.1.4 on 2021-01-03 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apilogic', '0028_remove_players_ped'),
    ]

    operations = [
        migrations.AlterField(
            model_name='derbyarenas',
            name='height_limit',
            field=models.DecimalField(db_column='height_limit', decimal_places=4, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='derbyarenasspawns',
            name='rotation',
            field=models.DecimalField(decimal_places=4, max_digits=6),
        ),
        migrations.AlterField(
            model_name='derbyarenasspawns',
            name='x',
            field=models.DecimalField(decimal_places=4, max_digits=6),
        ),
        migrations.AlterField(
            model_name='derbyarenasspawns',
            name='y',
            field=models.DecimalField(decimal_places=4, max_digits=6),
        ),
        migrations.AlterField(
            model_name='derbyarenasspawns',
            name='z',
            field=models.DecimalField(decimal_places=4, max_digits=6),
        ),
        migrations.AlterField(
            model_name='dmarenasspawns',
            name='x',
            field=models.DecimalField(decimal_places=4, max_digits=6),
        ),
        migrations.AlterField(
            model_name='dmarenasspawns',
            name='y',
            field=models.DecimalField(decimal_places=4, max_digits=6),
        ),
        migrations.AlterField(
            model_name='dmarenasspawns',
            name='z',
            field=models.DecimalField(decimal_places=4, max_digits=6),
        ),
        migrations.AlterField(
            model_name='heavydmarenasspawns',
            name='x',
            field=models.DecimalField(decimal_places=4, max_digits=6),
        ),
        migrations.AlterField(
            model_name='heavydmarenasspawns',
            name='y',
            field=models.DecimalField(decimal_places=4, max_digits=6),
        ),
        migrations.AlterField(
            model_name='heavydmarenasspawns',
            name='z',
            field=models.DecimalField(decimal_places=4, max_digits=6),
        ),
        migrations.AlterField(
            model_name='hideandseekarenas',
            name='looking_x',
            field=models.DecimalField(db_column='looking_x', decimal_places=4, max_digits=6),
        ),
        migrations.AlterField(
            model_name='hideandseekarenas',
            name='looking_y',
            field=models.DecimalField(db_column='looking_y', decimal_places=4, max_digits=6),
        ),
        migrations.AlterField(
            model_name='hideandseekarenas',
            name='looking_z',
            field=models.DecimalField(db_column='looking_z', decimal_places=4, max_digits=6),
        ),
        migrations.AlterField(
            model_name='hideandseekarenasspawns',
            name='x',
            field=models.DecimalField(decimal_places=4, max_digits=6),
        ),
        migrations.AlterField(
            model_name='hideandseekarenasspawns',
            name='y',
            field=models.DecimalField(decimal_places=4, max_digits=6),
        ),
        migrations.AlterField(
            model_name='hideandseekarenasspawns',
            name='z',
            field=models.DecimalField(decimal_places=4, max_digits=6),
        ),
        migrations.AlterField(
            model_name='oneshootarenasspawns',
            name='x',
            field=models.DecimalField(decimal_places=4, max_digits=6),
        ),
        migrations.AlterField(
            model_name='oneshootarenasspawns',
            name='y',
            field=models.DecimalField(decimal_places=4, max_digits=6),
        ),
        migrations.AlterField(
            model_name='oneshootarenasspawns',
            name='z',
            field=models.DecimalField(decimal_places=4, max_digits=6),
        ),
        migrations.AlterField(
            model_name='playersspawns',
            name='x',
            field=models.DecimalField(decimal_places=4, max_digits=6),
        ),
        migrations.AlterField(
            model_name='playersspawns',
            name='y',
            field=models.DecimalField(decimal_places=4, max_digits=6),
        ),
        migrations.AlterField(
            model_name='playersspawns',
            name='z',
            field=models.DecimalField(decimal_places=4, max_digits=6),
        ),
        migrations.AlterField(
            model_name='racearenascheckpoints',
            name='x',
            field=models.DecimalField(decimal_places=4, max_digits=6),
        ),
        migrations.AlterField(
            model_name='racearenascheckpoints',
            name='y',
            field=models.DecimalField(decimal_places=4, max_digits=6),
        ),
        migrations.AlterField(
            model_name='racearenascheckpoints',
            name='z',
            field=models.DecimalField(decimal_places=4, max_digits=6),
        ),
        migrations.AlterField(
            model_name='racearenasspawns',
            name='rotation',
            field=models.DecimalField(decimal_places=4, max_digits=6),
        ),
        migrations.AlterField(
            model_name='racearenasspawns',
            name='vehicle_model',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='racearenasspawns',
            name='x',
            field=models.DecimalField(decimal_places=4, max_digits=6),
        ),
        migrations.AlterField(
            model_name='racearenasspawns',
            name='y',
            field=models.DecimalField(decimal_places=4, max_digits=6),
        ),
        migrations.AlterField(
            model_name='racearenasspawns',
            name='z',
            field=models.DecimalField(decimal_places=4, max_digits=6),
        ),
        migrations.AlterField(
            model_name='sniperarenasspawns',
            name='x',
            field=models.DecimalField(decimal_places=4, max_digits=6),
        ),
        migrations.AlterField(
            model_name='sniperarenasspawns',
            name='y',
            field=models.DecimalField(decimal_places=4, max_digits=6),
        ),
        migrations.AlterField(
            model_name='sniperarenasspawns',
            name='z',
            field=models.DecimalField(decimal_places=4, max_digits=6),
        ),
        migrations.AlterField(
            model_name='tdmarenasspawns',
            name='x',
            field=models.DecimalField(decimal_places=4, max_digits=6),
        ),
        migrations.AlterField(
            model_name='tdmarenasspawns',
            name='y',
            field=models.DecimalField(decimal_places=4, max_digits=6),
        ),
        migrations.AlterField(
            model_name='tdmarenasspawns',
            name='z',
            field=models.DecimalField(decimal_places=4, max_digits=6),
        ),
    ]
