# Generated by Django 3.1.4 on 2021-01-04 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apilogic', '0030_auto_20210103_1502'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lootboxes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'lootboxes',
            },
        ),
        migrations.CreateModel(
            name='LootboxItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chance', models.SmallIntegerField()),
                ('display_name', models.CharField(max_length=64)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apilogic.items')),
                ('lootbox', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lootbox_items', to='apilogic.lootboxes')),
            ],
            options={
                'db_table': 'lootbox_items',
            },
        ),
        migrations.AddField(
            model_name='lootboxes',
            name='items',
            field=models.ManyToManyField(related_name='lootbox_items', through='apilogic.LootboxItems', to='apilogic.Items'),
        ),
    ]
