# Generated by Django 3.1.4 on 2021-01-04 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apilogic', '0031_auto_20210104_2152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lootboxitems',
            name='display_name',
        ),
        migrations.AddField(
            model_name='lootboxes',
            name='display_name',
            field=models.CharField(default='T', max_length=64),
            preserve_default=False,
        ),
    ]
