# Generated by Django 3.1.4 on 2021-01-04 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apilogic', '0032_auto_20210104_2154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lootboxes',
            name='display_name',
        ),
        migrations.AddField(
            model_name='lootboxes',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apilogic.items'),
        ),
    ]
