# Generated by Django 3.1.4 on 2021-01-04 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apilogic', '0034_auto_20210104_2333'),
    ]

    operations = [
        migrations.AddField(
            model_name='lootboxes',
            name='max_chance',
            field=models.SmallIntegerField(default=100),
            preserve_default=False,
        ),
    ]
