# Generated by Django 3.1.4 on 2021-01-06 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apilogic', '0035_lootboxes_max_chance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Objects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.DecimalField(decimal_places=4, max_digits=10)),
                ('y', models.DecimalField(decimal_places=4, max_digits=10)),
                ('z', models.DecimalField(decimal_places=4, max_digits=10)),
                ('rot_x', models.DecimalField(decimal_places=4, max_digits=10)),
                ('rot_y', models.DecimalField(decimal_places=4, max_digits=10)),
                ('rot_z', models.DecimalField(decimal_places=4, max_digits=10)),
                ('ragemp_object_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Vehicles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.DecimalField(decimal_places=4, max_digits=10)),
                ('y', models.DecimalField(decimal_places=4, max_digits=10)),
                ('z', models.DecimalField(decimal_places=4, max_digits=10)),
                ('rot_x', models.DecimalField(decimal_places=4, max_digits=10)),
                ('rot_y', models.DecimalField(decimal_places=4, max_digits=10)),
                ('rot_z', models.DecimalField(decimal_places=4, max_digits=10)),
                ('ragemp_vehicle_id', models.IntegerField()),
            ],
        ),
    ]
