# Generated by Django 3.1.4 on 2021-01-06 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apilogic', '0036_objects_vehicles'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='objects',
            table='objects',
        ),
        migrations.AlterModelTable(
            name='vehicles',
            table='vehicles',
        ),
    ]
