# Generated by Django 3.1.4 on 2021-01-06 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apilogic', '0037_auto_20210106_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objects',
            name='ragemp_object_id',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='ragemp_vehicle_id',
            field=models.PositiveIntegerField(),
        ),
    ]
