# Generated by Django 3.1.4 on 2021-01-08 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apilogic', '0038_auto_20210106_2246'),
    ]

    operations = [
        migrations.CreateModel(
            name='Levels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.SmallIntegerField()),
                ('required_exp', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'levels',
            },
        ),
        migrations.AddField(
            model_name='players',
            name='level',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='apilogic.levels'),
            preserve_default=False,
        ),
    ]
