# Generated by Django 3.1.4 on 2021-01-10 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apilogic', '0038_auto_20210106_2246'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teleports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.DecimalField(decimal_places=4, max_digits=10)),
                ('y', models.DecimalField(decimal_places=4, max_digits=10)),
                ('z', models.DecimalField(decimal_places=4, max_digits=10)),
                ('display_name', models.CharField(max_length=64)),
                ('alias', models.CharField(max_length=14)),
                ('heading', models.DecimalField(decimal_places=4, max_digits=10)),
            ],
            options={
                'db_table': 'teleports',
            },
        ),
    ]
