# Generated by Django 3.1.4 on 2021-01-08 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apilogic', '0039_auto_20210108_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='players',
            name='level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='apilogic.levels'),
        ),
    ]
