# Generated by Django 3.1.4 on 2021-01-09 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apilogic', '0040_auto_20210108_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='players',
            name='exp',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='levels',
            name='required_exp',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
